In [1]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display

In [2]:
rental_listing1 = pd.read_csv('/Users/shreya/Desktop/Comp_viz/Project/Zrent_listings.csv')
rental_listing2 = pd.read_csv('/Users/shreya/Desktop/Comp_viz/Project/Zrent_listings_BROKLINE.csv')
rental_listing3 = pd.read_csv('/Users/shreya/Desktop/Comp_viz/Project/Zrent_listings_CAMB.csv')

neighbourhood_zipcode_mapping = pd.read_csv('/Users/shreya/Desktop/Comp_viz/Project/Neighbourhood_zipcode.csv')

rental_listing = pd.concat([rental_listing1, rental_listing2, rental_listing3], axis=0)

In [3]:
landmarks_coordinates = {
    "Boston Common": {
        "latitude": 42.3551,
        "longitude": -71.0656
    },
    "Harvard University": {
        "latitude": 42.3770,
        "longitude": -71.1167
    },
    "Fenway Park": {
        "latitude": 42.3467,
        "longitude": -71.0972
    },
    "Seaport District": {
        "latitude": 42.3523,
        "longitude": -71.0483
    },
    "North End": {
        "latitude": 42.3645,
        "longitude": -71.0542
    },
    "Northeastern University": {
        "latitude": 42.3401,
        "longitude": -71.0892
    },
    "Boston University": {
        "latitude": 42.3505,
        "longitude": -71.1050
    }
}

In [4]:
rental_listing.columns = rental_listing.columns.str.strip()
print(rental_listing.columns)
print(neighbourhood_zipcode_mapping.columns)

Index(['Street Address', 'Street Name', 'Zipcode', 'City', 'State', 'Latitude',
       'Longitude', 'Price', 'Listing Type', 'Home Type', 'ZPID', 'Area',
       'Bedrooms', 'Bathrooms', 'Unit', 'Floor', 'Block', 'Time on Zillow',
       'Is Non-Owner Occupied', 'Is Zillow Owned', 'Days on Zillow',
       'Is Showcase Listing'],
      dtype='object')
Index(['Neighbourhood', 'Zip_Code'], dtype='object')

In [5]:
rental_listing

,Street Address,Street Name,Zipcode,City,State,Latitude,Longitude,Price,Listing Type,Home Type,...,Bedrooms,Bathrooms,Unit,Floor,Block,Time on Zillow,Is Non-Owner Occupied,Is Zillow Owned,Days on Zillow,Is Showcase Listing
0,650 Columbus Ave #434,650 Columbus Ave #434,2118,Boston,MA,42.338590,-71.083120,3300,FOR_RENT,APARTMENT,...,1,1,# 434,6,7,3200409000,true,false,-1,false
1,8 Winter St #1103,8 Winter St #1103,2108,Boston,MA,42.355520,-71.061660,3200,FOR_RENT,APARTMENT,...,1,1,# 1103,10,3,4057882000,true,false,-1,false
2,475 Shawmut Ave APT 2,475 Shawmut Ave APT 2,2118,Boston,MA,42.338947,-71.075890,3500,FOR_RENT,APARTMENT,...,2,1,Apt 2,2,5,351695000,true,false,-1,false
3,780 William T Morrissey Blvd #1B-1BA-644SQFT,780 William T Morrissey Blvd #1B-1BA-644SQFT,2122,Dorchester,MA,42.295498,-71.046715,3158,FOR_RENT,APARTMENT,...,1,1,# 1B-1Ba-644Sqft,10,1,4477663000,true,false,-1,false
4,1079 Commonwealth Ave APT 532,1079 Commonwealth Ave APT 532,2215,Boston,MA,42.352787,-71.124510,4700,FOR_RENT,APARTMENT,...,3,2,Apt 532,10,6,1646314000,true,false,-1,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6570,340 Putnam Ave #2,340 Putnam Ave #2,2139,Cambridge,MA,42.361565,-71.113335,4000,FOR_RENT,APARTMENT,...,3,1,# 2,10,8,189407000,true,false,-1,false
6571,3 Ellery St #3D,3 Ellery St #3D,2138,Cambridge,MA,42.369770,-71.111930,2700,FOR_RENT,APARTMENT,...,1,1,# 3D,8,4,965521000,true,false,-1,false
6572,1427 Cambridge St #4,1427 Cambridge St #4,2139,Cambridge,MA,42.374050,-71.101875,4700,FOR_RENT,APARTMENT,...,3,1,# 4,2,2,1312902000,true,false,-1,false
6573,10 Cambridge Ter #1F,10 Cambridge Ter #1F,2140,Cambridge,MA,42.388080,-71.122600,5000,FOR_RENT,APARTMENT,...,4,2,# 1F,10,1,25156377000,true,false,-1,false
6574,25 Plymouth St TOWNHOUSE 2,25 Plymouth St TOWNHOUSE 2,2141,Cambridge,MA,42.368850,-71.091870,3450,FOR_RENT,APARTMENT,...,2,1,Townhouse 2,10,3,442450000,true,false,-1,false

In [6]:
neighbourhood_zipcode_mapping['Zip_Code'] = neighbourhood_zipcode_mapping['Zip_Code'].apply(
    lambda x: list(map(int, x.split(',')))
)
# Display the updated DataFrame
print(neighbourhood_zipcode_mapping)

             Neighbourhood                                           Zip_Code
0                  Allston                                             [2134]
1                 Back Bay                                 [2116, 2117, 2199]
2              Beacon Hill                                             [2108]
3                 Brighton                                             [2135]
4              Charlestown                                             [2129]
5                Chinatown                                             [2111]
6               Dorchester                           [2121, 2122, 2124, 2125]
7          Downtown Boston                                       [2109, 2110]
8              East Boston                                             [2128]
9           Fenway/Kenmore                                       [2215, 2115]
10               Hyde Park                                             [2136]
11           Jamaica Plain                                             [2130]
12                Mattapan                                             [2126]
13            Mission Hill                                             [2120]
14               North End                                             [2113]
15              Roslindale                                             [2131]
16                 Roxbury                                             [2119]
17        Seaport District                                             [2210]
18  South Boston (Southie)                                       [2127, 2210]
19               South End                                             [2118]
20                West End                                             [2114]
21            West Roxbury                                             [2132]
22               Cambridge                     [2138, 2139, 2140, 2141, 2142]
23              Somerville                                 [2143, 2144, 2145]
24               Brookline                                       [2445, 2446]
25                  Quincy                                 [2169, 2170, 2171]
26                 Medford                                             [2155]
27               Watertown                                             [2472]
28                  Newton  [2458, 2459, 2460, 2461, 2462, 2464, 2465, 246...
29                  Malden                                             [2148]
30                 Everett                                             [2149]
31               Arlington                                       [2474, 2476]
32                 Chelsea                                             [2150]
33                  Revere                                             [2151]
34                  Milton                                             [2186]
35                 Belmont                                             [2478]
36                 Waltham                                 [2451, 2452, 2453]
37                  Woburn                                             [1801]
38               Lexington                                       [2420, 2421]
39                Winthrop                                             [2152]
40                 Melrose                                             [2176]
41                 Needham                                       [2492, 2494]

In [7]:
neighbourhood_mapping = neighbourhood_zipcode_mapping.explode('Zip_Code')
neighbourhood_mapping['Zip_Code'] = neighbourhood_mapping['Zip_Code'].astype(int)

In [8]:
zipcodes_in_boston = neighbourhood_mapping['Zip_Code'].tolist()
zipcodes_in_rental_listing = rental_listing['Zipcode'].tolist()
zipcodes_in_rental_listing = pd.Series(zipcodes_in_rental_listing).unique().tolist()
zipcodes_not_covered = [item for item in zipcodes_in_boston if item not in zipcodes_in_rental_listing]
neighbourhoods_not_covered = neighbourhood_mapping[neighbourhood_mapping['Zip_Code'].isin(zipcodes_not_covered)]

# Convert the result to a dictionary for easy mapping
zipcode_to_neighbourhood = neighbourhood_mapping.set_index('Zip_Code')['Neighbourhood'].to_dict()

# Display the mapping
print(neighbourhoods_not_covered)

             Neighbourhood  Zip_Code
1                 Back Bay      2117
1                 Back Bay      2199
4              Charlestown      2129
6               Dorchester      2121
6               Dorchester      2125
7          Downtown Boston      2110
15              Roslindale      2131
17        Seaport District      2210
18  South Boston (Southie)      2210
23              Somerville      2144
23              Somerville      2145
25                  Quincy      2169
25                  Quincy      2170
25                  Quincy      2171
26                 Medford      2155
27               Watertown      2472
28                  Newton      2458
28                  Newton      2459
28                  Newton      2460
28                  Newton      2461
28                  Newton      2462
28                  Newton      2464
28                  Newton      2465
28                  Newton      2466
28                  Newton      2468
29                  Malden      2148
30                 Everett      2149
31               Arlington      2474
31               Arlington      2476
32                 Chelsea      2150
33                  Revere      2151
34                  Milton      2186
35                 Belmont      2478
36                 Waltham      2451
36                 Waltham      2452
36                 Waltham      2453
37                  Woburn      1801
38               Lexington      2420
38               Lexington      2421
39                Winthrop      2152
40                 Melrose      2176
41                 Needham      2492
41                 Needham      2494

In [9]:
neighbourhood_mapping.to_excel('output_file1.xlsx', index=False, engine='openpyxl')  # Save as .xlsx

In [10]:
rental_listing = rental_listing.merge(neighbourhood_mapping, left_on='Zipcode', right_on='Zip_Code', how='left')

# Step 3: Drop the Zip_code column if no longer needed
rental_listing.drop(columns=['Zip_Code'], inplace=True)

# Display the updated rental_listing DataFrame
print(len(rental_listing))

18120

In [11]:
rental_listing.to_excel('output_file.xlsx', index=False, engine='openpyxl')  # Save as .xlsx